#!/usr/bin/env node
/**
 * 将 breeds JSON 中的 pinyin 字段重命名为 name_cn，并填充中文翻译
 *
 * 用法: node scripts/translate-breeds.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = resolve(__dirname, "../data/breeds");

// ─── 猫品种中文名映射 ─────────────────────────────────────────
const CAT_NAMES_CN = {
  "Abyssinian": "阿比西尼亚猫",
  "American Bobtail": "美国短尾猫",
  "American Curl": "美国卷耳猫",
  "American Shorthair": "美国短毛猫",
  "American Wirehair": "美国硬毛猫",
  "Balinese": "巴厘猫",
  "Bengal": "孟加拉猫",
  "Birman": "伯曼猫",
  "Bombay": "孟买猫",
  "British Shorthair": "英国短毛猫",
  "Burmese": "缅甸猫",
  "Burmilla": "波米拉猫",
  "Chartreux": "沙特尔猫",
  "Colorpoint Shorthair": "重点色短毛猫",
  "Cornish Rex": "柯尼斯卷毛猫",
  "Devon Rex": "德文卷毛猫",
  "Egyptian Mau": "埃及猫",
  "European Burmese": "欧洲缅甸猫",
  "Exotic": "异国短毛猫",
  "Havana Brown": "哈瓦那棕猫",
  "Japanese Bobtail": "日本短尾猫",
  "Khao Manee": "考拉猫",
  "Korat": "科拉特猫",
  "Laperm": "拉邦猫",
  "Lykoi": "狼猫",
  "Maine Coon": "缅因猫",
  "Manx": "马恩岛猫",
  "Norwegian Forest Cat": "挪威森林猫",
  "Ocicat": "奥西猫",
  "Oriental": "东方猫",
  "Persian": "波斯猫",
  "RagaMuffin": "拉格多尔猫",
  "Ragdoll": "布偶猫",
  "Russian Blue": "俄罗斯蓝猫",
  "Scottish Fold": "苏格兰折耳猫",
  "Selkirk Rex": "塞尔凯克卷毛猫",
  "Siamese": "暹罗猫",
  "Siberian": "西伯利亚猫",
  "Singapura": "新加坡猫",
  "Somali": "索马里猫",
  "Sphynx": "斯芬克斯猫",
  "Tonkinese": "东奇尼猫",
  "Toybob": "玩具短尾猫",
  "Turkish Angora": "土耳其安哥拉猫",
  "Turkish Van": "土耳其梵猫",
};

// ─── 狗品种中文名映射 ─────────────────────────────────────────
const DOG_NAMES_CN = {
  "Affenpinscher": "艾芬笃宾犬",
  "Afghan Hound": "阿富汗猎犬",
  "Airedale Terrier": "万能梗",
  "Akita": "秋田犬",
  "Alaskan Klee Kai": "阿拉斯加克利凯犬",
  "Alaskan Malamute": "阿拉斯加雪橇犬",
  "American Bulldog": "美国斗牛犬",
  "American English Coonhound": "美国英国猎浣熊犬",
  "American Eskimo Dog": "美国爱斯基摩犬",
  "American Foxhound": "美国猎狐犬",
  "American Hairless Terrier": "美国无毛梗",
  "American Leopard Hound": "美国豹猎犬",
  "American Staffordshire Terrier": "美国斯塔福德郡梗",
  "American Water Spaniel": "美国水猎犬",
  "Anatolian Shepherd Dog": "安纳托利亚牧羊犬",
  "Appenzeller Sennenhund": "阿彭策尔山地犬",
  "Australian Cattle Dog": "澳大利亚牧牛犬",
  "Australian Kelpie": "澳大利亚卡尔比犬",
  "Australian Shepherd": "澳大利亚牧羊犬",
  "Australian Stumpy Tail Cattle Dog": "澳大利亚短尾牧牛犬",
  "Australian Terrier": "澳大利亚梗",
  "Azawakh": "阿扎瓦克犬",
  "Barbado da Terceira": "特塞拉岛波达多犬",
  "Barbet": "法国水犬",
  "Basenji": "巴辛吉犬",
  "Basset Fauve de Bretagne": "布列塔尼黄褐矮腿猎犬",
  "Basset Hound": "巴吉度猎犬",
  "Bavarian Mountain Scent Hound": "巴伐利亚山地嗅觉猎犬",
  "Beagle": "比格犬",
  "Bearded Collie": "古代长须牧羊犬",
  "Beauceron": "波色龙犬",
  "Bedlington Terrier": "贝灵顿梗",
  "Belgian Laekenois": "比利时拉克诺斯犬",
  "Belgian Malinois": "比利时马林诺斯犬",
  "Belgian Sheepdog": "比利时牧羊犬",
  "Belgian Tervuren": "比利时特伏丹犬",
  "Bergamasco Sheepdog": "贝加马斯科牧羊犬",
  "Berger Picard": "匹卡德牧羊犬",
  "Bernese Mountain Dog": "伯恩山犬",
  "Bichon Frise": "比熊犬",
  "Biewer Terrier": "比弗梗",
  "Black and Tan Coonhound": "黑褐猎浣熊犬",
  "Black Russian Terrier": "黑俄罗斯梗",
  "Bloodhound": "寻血猎犬",
  "Blue Picardy Spaniel": "蓝色皮卡第猎犬",
  "Bluetick Coonhound": "蓝斑猎浣熊犬",
  "Boerboel": "南非獒犬",
  "Bohemian Shepherd": "波西米亚牧羊犬",
  "Bolognese": "波洛尼亚犬",
  "Border Collie": "边境牧羊犬",
  "Border Terrier": "边境梗",
  "Borzoi": "俄罗斯猎狼犬",
  "Boston Terrier": "波士顿梗",
  "Bouvier des Ardennes": "阿登牧牛犬",
  "Bouvier des Flandres": "法兰德斯牧牛犬",
  "Boxer": "拳师犬",
  "Boykin Spaniel": "博伊金猎犬",
  "Bracco Italiano": "意大利布拉可犬",
  "Braque du Bourbonnais": "波旁指示犬",
  "Braque Francais Pyrenean": "比利牛斯法国指示犬",
  "Braque Saint-Germain": "圣日耳曼指示犬",
  "Brazilian Terrier": "巴西梗",
  "Briard": "布里犬",
  "Brittany": "布列塔尼犬",
  "Broholmer": "布罗霍尔默犬",
  "Brussels Griffon": "布鲁塞尔格里芬犬",
  "Bull Terrier": "牛头梗",
  "Bulldog": "斗牛犬",
  "Bullmastiff": "斗牛獒犬",
  "Cairn Terrier": "凯恩梗",
  "Calupoh": "卡卢波犬",
  "Canaan Dog": "迦南犬",
  "Canadian Eskimo Dog": "加拿大爱斯基摩犬",
  "Cane Corso": "卡斯罗犬",
  "Cardigan Welsh Corgi": "卡迪根威尔士柯基犬",
  "Carolina Dog": "卡罗莱纳犬",
  "Catahoula Leopard Dog": "卡塔霍拉豹纹犬",
  "Caucasian Shepherd Dog": "高加索牧羊犬",
  "Cavalier King Charles Spaniel": "骑士查理王小猎犬",
  "Central Asian Shepherd Dog": "中亚牧羊犬",
  "Cesky Terrier": "捷克梗",
  "Chesapeake Bay Retriever": "切萨皮克湾寻回犬",
  "Chihuahua": "吉娃娃",
  "Chinese Crested": "中国冠毛犬",
  "Chinese Shar-Pei": "中国沙皮犬",
  "Chinook": "奇努克犬",
  "Chow Chow": "松狮犬",
  "Cirneco dell'Etna": "埃特纳火山犬",
  "Clumber Spaniel": "克伦伯猎犬",
  "Cocker Spaniel": "可卡犬",
  "Collie": "柯利牧羊犬",
  "Coton de Tulear": "图莱亚尔棉毛犬",
  "Croatian Sheepdog": "克罗地亚牧羊犬",
  "Curly-Coated Retriever": "卷毛寻回犬",
  "Czechoslovakian Vlciak": "捷克斯洛伐克狼犬",
  "Dachshund": "腊肠犬",
  "Dalmatian": "斑点犬",
  "Dandie Dinmont Terrier": "丹迪丁蒙梗",
  "Danish-Swedish Farmdog": "丹麦瑞典农场犬",
  "Deutscher Wachtelhund": "德国鹌鹑犬",
  "Doberman Pinscher": "杜宾犬",
  "Dogo Argentino": "阿根廷杜高犬",
  "Dogue de Bordeaux": "波尔多犬",
  "Drentsche Patrijshond": "荷兰海鸥犬",
  "Drever": "瑞士猎犬",
  "Dutch Shepherd": "荷兰牧羊犬",
  "English Cocker Spaniel": "英国可卡犬",
  "English Foxhound": "英国猎狐犬",
  "English Setter": "英国雪达犬",
  "English Springer Spaniel": "英国史宾格犬",
  "English Toy Spaniel": "英国玩具猎犬",
  "Entlebucher Mountain Dog": "恩特莱布赫山地犬",
  "Estrela Mountain Dog": "埃什特雷拉山地犬",
  "Eurasier": "欧亚犬",
  "Field Spaniel": "田野猎犬",
  "Finnish Lapphund": "芬兰拉普猎犬",
  "Finnish Spitz": "芬兰尖嘴犬",
  "Flat-Coated Retriever": "平毛寻回犬",
  "French Bulldog": "法国斗牛犬",
  "French Spaniel": "法国猎犬",
  "German Longhaired Pointer": "德国长毛指示犬",
  "German Pinscher": "德国平犬",
  "German Shepherd Dog": "德国牧羊犬",
  "German Shorthaired Pointer": "德国短毛指示犬",
  "German Spitz": "德国尖嘴犬",
  "German Wirehaired Pointer": "德国硬毛指示犬",
  "Giant Schnauzer": "巨型雪纳瑞",
  "Glen of Imaal Terrier": "伊马谷梗",
  "Golden Retriever": "金毛寻回犬",
  "Gordon Setter": "戈登雪达犬",
  "Grand Basset Griffon Vendéen": "大格里芬旺代犬",
  "Great Dane": "大丹犬",
  "Great Pyrenees": "大白熊犬",
  "Greater Swiss Mountain Dog": "大瑞士山地犬",
  "Greyhound": "灵缇犬",
  "Hamiltonstovare": "汉密尔顿斯道弗犬",
  "Hanoverian Scenthound": "汉诺威嗅觉猎犬",
  "Harrier": "哈里犬",
  "Havanese": "哈瓦那犬",
  "Hokkaido": "北海道犬",
  "Hovawart": "霍瓦瓦特犬",
  "Ibizan Hound": "伊比赞猎犬",
  "Icelandic Sheepdog": "冰岛牧羊犬",
  "Irish Red and White Setter": "爱尔兰红白雪达犬",
  "Irish Setter": "爱尔兰雪达犬",
  "Irish Terrier": "爱尔兰梗",
  "Irish Water Spaniel": "爱尔兰水猎犬",
  "Irish Wolfhound": "爱尔兰猎狼犬",
  "Italian Greyhound": "意大利灵缇犬",
  "Jagdterrier": "猎梗",
  "Japanese Akitainu": "日本秋田犬",
  "Japanese Chin": "日本狆",
  "Japanese Spitz": "日本尖嘴犬",
  "Japanese Terrier": "日本梗",
  "Kai Ken": "甲斐犬",
  "Karelian Bear Dog": "卡累利阿熊犬",
  "Keeshond": "荷兰毛狮犬",
  "Kerry Blue Terrier": "凯利蓝梗",
  "Kishu Ken": "纪州犬",
  "Komondor": "可蒙犬",
  "Korean Jindo Dog": "韩国珍岛犬",
  "Kromfohrlander": "克龙福尔兰德犬",
  "Kuvasz": "库瓦兹犬",
  "Labrador Retriever": "拉布拉多寻回犬",
  "Lagotto Romagnolo": "拉戈托罗马阁挪露犬",
  "Lakeland Terrier": "湖畔梗",
  "Lancashire Heeler": "兰开夏赫勒犬",
  "Lapponian Herder": "拉普兰牧犬",
  "Large Munsterlander": "大蒙斯特兰德犬",
  "Leonberger": "莱昂伯格犬",
  "Lhasa Apso": "拉萨犬",
  "Löwchen": "罗秦犬",
  "Lowchen": "罗秦犬",
  "Maltese": "马尔济斯犬",
  "Manchester Terrier": "曼彻斯特梗",
  "Manchester Terrier (Standard)": "标准曼彻斯特梗",
  "Manchester Terrier (Toy)": "玩具曼彻斯特梗",
  "Maremma Sheepdog": "马瑞马牧羊犬",
  "Mastiff": "獒犬",
  "McNab": "麦克纳布犬",
  "Miniature American Shepherd": "迷你美国牧羊犬",
  "Miniature Bull Terrier": "迷你牛头梗",
  "Miniature Pinscher": "迷你品犬",
  "Miniature Schnauzer": "迷你雪纳瑞",
  "Mountain Cur": "山犬",
  "Mudi": "穆迪犬",
  "Neapolitan Mastiff": "那不勒斯獒犬",
  "Nederlandse Kooikerhondje": "荷兰克伊克犬",
  "Newfoundland": "纽芬兰犬",
  "Norfolk Terrier": "诺福克梗",
  "Norrbottenspets": "北博滕犬",
  "Northern Inuit Dog": "北方因纽特犬",
  "Norwegian Buhund": "挪威布哈德犬",
  "Norwegian Elkhound": "挪威猎犬",
  "Norwegian Lundehund": "挪威卢德猎犬",
  "Norwich Terrier": "诺维奇梗",
  "Nova Scotia Duck Tolling Retriever": "新斯科舍诱鸭寻回犬",
  "Old Danish Pointer": "古老丹麦指示犬",
  "Old English Sheepdog": "古代英国牧羊犬",
  "Old English Terrier": "古代英国梗",
  "Otterhound": "水獭猎犬",
  "Papillon": "蝴蝶犬",
  "Parson Russell Terrier": "帕森罗塞尔梗",
  "Patterdale Terrier": "帕特代尔梗",
  "Pekingese": "北京犬",
  "Pembroke Welsh Corgi": "彭布罗克威尔士柯基犬",
  "Peruvian Inca Orchid": "秘鲁无毛犬",
  "Petit Basset Griffon Vendéen": "小格里芬旺代犬",
  "Pharaoh Hound": "法老王猎犬",
  "Plott": "普罗特猎犬",
  "Plott Hound": "普罗特猎犬",
  "Pointer": "指示犬",
  "Polish Lowland Sheepdog": "波兰低地牧羊犬",
  "Pomeranian": "博美犬",
  "Pont-Audemer Spaniel": "蓬奥德梅猎犬",
  "Poodle": "贵宾犬",
  "Poodle (Miniature)": "迷你贵宾犬",
  "Poodle (Standard)": "标准贵宾犬",
  "Poodle (Toy)": "玩具贵宾犬",
  "Porcelaine": "瓷犬",
  "Portuguese Podengo": "葡萄牙波登可犬",
  "Portuguese Podengo Pequeno": "迷你葡萄牙波登可犬",
  "Portuguese Pointer": "葡萄牙指示犬",
  "Portuguese Sheepdog": "葡萄牙牧羊犬",
  "Portuguese Water Dog": "葡萄牙水犬",
  "Presa Canario": "加纳利犬",
  "Pudelpointer": "普德尔指示犬",
  "Pug": "巴哥犬",
  "Puli": "波利犬",
  "Pumi": "波密犬",
  "Pyrenean Mastiff": "比利牛斯獒犬",
  "Pyrenean Shepherd": "比利牛斯牧羊犬",
  "Rafeiro do Alentejo": "阿连特茹獒犬",
  "Rat Terrier": "鼠梗",
  "Redbone Coonhound": "红骨猎浣熊犬",
  "Rhodesian Ridgeback": "罗得西亚脊背犬",
  "Romanian Carpathian Shepherd": "罗马尼亚喀尔巴阡牧羊犬",
  "Romanian Mioritic Shepherd Dog": "罗马尼亚米奥里蒂克牧羊犬",
  "Rottweiler": "罗威纳犬",
  "Russell Terrier": "罗塞尔梗",
  "Russian Toy": "俄罗斯玩具犬",
  "Russian Tsvetnaya Bolonka": "俄罗斯彩色博洛犬",
  "Saarloos Wolfhond": "萨尔路斯狼犬",
  "Saint Bernard": "圣伯纳犬",
  "Saluki": "萨路基猎犬",
  "Samoyed": "萨摩耶犬",
  "Schapendoes": "荷兰牧羊犬",
  "Schillerstovare": "席勒猎犬",
  "Schipperke": "西帕基犬",
  "Scottish Deerhound": "苏格兰猎鹿犬",
  "Scottish Terrier": "苏格兰梗",
  "Sealyham Terrier": "西里汉梗",
  "Segugio Italiano": "意大利塞古犬",
  "Shetland Sheepdog": "设得兰牧羊犬",
  "Shiba Inu": "柴犬",
  "Shih Tzu": "西施犬",
  "Shikoku": "四国犬",
  "Shikoku Ken": "四国犬",
  "Siberian Husky": "西伯利亚哈士奇",
  "Silken Windhound": "丝风犬",
  "Silky Terrier": "丝毛梗",
  "Skye Terrier": "斯凯梗",
  "Sloughi": "斯洛吉犬",
  "Slovakian Wirehaired Pointer": "斯洛伐克硬毛指示犬",
  "Slovensky Cuvac": "斯洛伐克楚瓦克犬",
  "Slovensky Kopov": "斯洛伐克猎犬",
  "Small Munsterlander": "小蒙斯特兰德犬",
  "Smooth Fox Terrier": "平毛猎狐梗",
  "Soft Coated Wheaten Terrier": "软毛麦色梗",
  "Spanish Mastiff": "西班牙獒犬",
  "Spanish Water Dog": "西班牙水犬",
  "Spinone Italiano": "意大利斯皮诺犬",
  "St. Bernard": "圣伯纳犬",
  "Stabyhoun": "斯塔比猎犬",
  "Staffordshire Bull Terrier": "斯塔福德郡斗牛梗",
  "Standard Schnauzer": "标准雪纳瑞",
  "Sussex Spaniel": "苏塞克斯猎犬",
  "Swedish Elkhound": "瑞典猎犬",
  "Swedish Lapphund": "瑞典拉普猎犬",
  "Swedish Vallhund": "瑞典柯基犬",
  "Taiwan Dog": "台湾犬",
  "Teddy Roosevelt Terrier": "泰迪罗斯福梗",
  "Thai Bangkaew": "泰国班克犬",
  "Thai Bangkaew Dog": "泰国班克犬",
  "Thai Ridgeback": "泰国脊背犬",
  "Tibetan Mastiff": "藏獒",
  "Tibetan Spaniel": "西藏猎犬",
  "Tibetan Terrier": "西藏梗",
  "Tornjak": "托尔雅克犬",
  "Tosa": "土佐犬",
  "Tosa Inu": "土佐犬",
  "Toy Fox Terrier": "玩具猎狐梗",
  "Toy Manchester Terrier": "玩具曼彻斯特梗",
  "Transylvanian Hound": "特兰西瓦尼亚猎犬",
  "Treeing Tennessee Brindle": "田纳西树纹犬",
  "Treeing Walker Coonhound": "步行猎浣熊犬",
  "Vizsla": "维兹拉犬",
  "Volpino Italiano": "意大利狐狸犬",
  "Weimaraner": "威玛猎犬",
  "Welsh Springer Spaniel": "威尔士史宾格犬",
  "Welsh Terrier": "威尔士梗",
  "West Highland White Terrier": "西高地白梗",
  "Wetterhoun": "荷兰水猎犬",
  "Whippet": "惠比特犬",
  "White Shepherd": "白色牧羊犬",
  "Wire Fox Terrier": "刚毛猎狐梗",
  "Wirehaired Pointing Griffon": "硬毛指示格里芬犬",
  "Wirehaired Vizsla": "硬毛维兹拉犬",
  "Working Kelpie": "工作卡尔比犬",
  "Xoloitzcuintli": "墨西哥无毛犬",
  "Yakutian Laika": "雅库特莱卡犬",
  "Yorkshire Terrier": "约克夏梗",
};

// ─── 工具函数：修复 JSON 解析后的双转义 Unicode ──────────────
function normalizeName(name) {
  return name
    .replace(/\\u00e9/g, "é")
    .replace(/\\u00f6/g, "ö")
    .replace(/\\u00f3/g, "ó")
    .replace(/\\u00e0/g, "à")
    .replace(/\\u00f1/g, "ñ");
}

// ─── 主流程 ────────────────────────────────────────────────────
function processFile(filePath, nameMap) {
  const raw = readFileSync(filePath, "utf-8");
  const breeds = JSON.parse(raw);

  let filled = 0;
  let missing = [];

  for (const breed of breeds) {
    // 修复 JSON 中的双转义 Unicode，并更新 name
    breed.name = normalizeName(breed.name);
    const cnName = nameMap[breed.name] ?? "";

    // 重命名 pinyin -> name_cn
    delete breed.pinyin;
    breed.name_cn = cnName;

    if (cnName) {
      filled++;
    } else {
      missing.push(engName);
    }
  }

  writeFileSync(filePath, JSON.stringify(breeds, null, 2) + "\n", "utf-8");

  console.log(`\n✓ ${filePath}`);
  console.log(`  总条目: ${breeds.length}, 已翻译: ${filled}`);
  if (missing.length > 0) {
    console.log(`  ⚠️  缺少中文名 (${missing.length}):`);
    missing.forEach((n) => console.log(`    - ${n}`));
  }
}

// ─── 执行 ──────────────────────────────────────────────────────
const catsPath = resolve(DATA_DIR, "cats.json");
const dogsPath = resolve(DATA_DIR, "dogs.json");

processFile(catsPath, CAT_NAMES_CN);
processFile(dogsPath, DOG_NAMES_CN);

console.log("\n🎉 全部处理完成！");
